# embed.cmake - bundle one page's sources into one self-contained page,
# gzip it, and emit it as C: the compressed bytes in .rodata plus the two
# lengths the daemon needs to inflate them.
# Copyright 2026 514 LLC d/b/a OpenGlow
# Written by Scott Wiederhold
# SPDX-License-Identifier: MIT
#
# Run by CMakeLists.txt as a custom command, once per page:
#   cmake -DUI_DIR=<src/ui> -DPAGE=<index|wizard|login>
#         -DOUT_HTML=<bundled page> -DOUT_C=<blob.c> -P embed.cmake
#
# Every stylesheet and script the page links is inlined in place of its
# tag, in the order listed below for that page (the order the page loads
# them), so the daemon serves exactly one response with no external
# assets; the token placeholder in the page's script survives untouched
# for main.c to substitute once the page is inflated. The bundled page
# is also written out uncompressed (OUT_HTML) for inspection; it is what
# tools/devserver.py --bundle serves. The pages live compressed in the
# binary because the rootfs is raw ext4: bytes in .rodata are bytes on
# the image. The gzip is deterministic (-n: no name, no timestamp), so
# the blob, and the binary, reproduce from the same sources.

foreach(v UI_DIR PAGE OUT_HTML OUT_C)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "embed.cmake: ${v} not set")
  endif()
endforeach()

if(PAGE STREQUAL "index")
  set(CSS_FILES vendor/bootstrap.min.css theme.css)
  set(JS_FILES vendor/bootstrap.bundle.min.js regions.js md.js help.js forms.js panel.js)
elseif(PAGE STREQUAL "wizard")
  set(CSS_FILES vendor/bootstrap.min.css theme.css wizard.css)
  set(JS_FILES vendor/bootstrap.bundle.min.js regions.js md.js wizard.js)
elseif(PAGE STREQUAL "login")
  set(CSS_FILES vendor/bootstrap.min.css theme.css wizard.css)
  set(JS_FILES login.js)
else()
  message(FATAL_ERROR "embed.cmake: unknown page ${PAGE}")
endif()

file(READ "${UI_DIR}/${PAGE}.html" HTML)
foreach(f ${CSS_FILES})
  set(tag "<link rel=\"stylesheet\" href=\"${f}\" />")
  string(FIND "${HTML}" "${tag}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "embed.cmake: ${PAGE}.html lacks the marker ${tag}")
  endif()
  file(READ "${UI_DIR}/${f}" BODY)
  string(REPLACE "${tag}" "<style>\n${BODY}</style>" HTML "${HTML}")
endforeach()
foreach(f ${JS_FILES})
  set(tag "<script src=\"${f}\"></script>")
  string(FIND "${HTML}" "${tag}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "embed.cmake: ${PAGE}.html lacks the marker ${tag}")
  endif()
  file(READ "${UI_DIR}/${f}" BODY)
  string(REPLACE "${tag}" "<script>\n${BODY}</script>" HTML "${HTML}")
endforeach()
file(WRITE "${OUT_HTML}" "${HTML}")
string(LENGTH "${HTML}" HTML_LEN)

find_program(GZIP_EXE gzip)
if(NOT GZIP_EXE)
  message(FATAL_ERROR "embed.cmake: gzip not found")
endif()
set(OUT_GZ "${OUT_HTML}.gz")
execute_process(COMMAND "${GZIP_EXE}" -9 -n -c
                INPUT_FILE "${OUT_HTML}" OUTPUT_FILE "${OUT_GZ}"
                RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "embed.cmake: gzip failed (${rc})")
endif()

# Byte array, 16 per line.
file(READ "${OUT_GZ}" HEX HEX)
string(LENGTH "${HEX}" HEX_LEN)
math(EXPR GZ_LEN "${HEX_LEN} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," HEX "${HEX}")
set(B "0x[0-9a-f][0-9a-f],")
string(REGEX REPLACE "(${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B})"
       "\\1\n" HEX "${HEX}")
file(WRITE "${OUT_C}"
"/* Generated by src/ui/embed.cmake from src/ui/${PAGE}.html - do not edit. */
#include \"ui.h\"

const unsigned char ${PAGE}_html_gz[] = {
${HEX}
};
const unsigned int ${PAGE}_html_gz_len = ${GZ_LEN};
const unsigned int ${PAGE}_html_len = ${HTML_LEN};
")
