# embed_docs.cmake - compile the advisory documents into C byte arrays.
# Copyright 2026 514 LLC d/b/a OpenGlow
# Written by Scott Wiederhold
# SPDX-License-Identifier: MIT
#
# Run by CMakeLists.txt as a custom command:
#   cmake -DDOCS_DIR=<docs/advisories> -DOUT_C=<advisories_blob.c> -P embed_docs.cmake
#
# Every docs/advisories/<id>.md becomes `advisory_<id>[]` (the bytes,
# unterminated) and `advisory_<id>_len`, in the fixed order below, which
# is the order the wizard shows them. The texts are small and read as
# plain markdown by the page, so they are stored uncompressed.

foreach(v DOCS_DIR OUT_C)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "embed_docs.cmake: ${v} not set")
  endif()
endforeach()

set(DOC_IDS safety-and-risk licenses privacy cloud-service)

set(BODY "/* Generated by src/ui/embed_docs.cmake from docs/advisories/ - do not edit. */\n#include <stddef.h>\n\n")
foreach(id ${DOC_IDS})
  set(f "${DOCS_DIR}/${id}.md")
  if(NOT EXISTS "${f}")
    message(FATAL_ERROR "embed_docs.cmake: missing ${f}")
  endif()
  file(READ "${f}" HEX HEX)
  string(LENGTH "${HEX}" HEX_LEN)
  math(EXPR LEN "${HEX_LEN} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," HEX "${HEX}")
  set(B "0x[0-9a-f][0-9a-f],")
  string(REGEX REPLACE "(${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B}${B})"
         "\\1\n" HEX "${HEX}")
  string(REPLACE "-" "_" sym "${id}")
  string(APPEND BODY "const unsigned char advisory_${sym}[] = {\n${HEX}\n};\n")
  string(APPEND BODY "const size_t advisory_${sym}_len = ${LEN};\n\n")
endforeach()
file(WRITE "${OUT_C}" "${BODY}")
