/*
 * font_hershey.h - the stroke font of the commissioning sheet
 * Copyright (c) 2026 Scott Wiederhold <s.e.wiederhold@gmail.com>
 * SPDX-License-Identifier: MIT
 *
 * Hershey Sans 1-stroke (Simplex): the printable ASCII glyphs (32 to
 * 126) as polylines in the font's own units, y up, the baseline at 0
 * and the cap height at HERSHEY_CAP. A glyph is a run of points in
 * hershey_pts starting at `first`, `count` long; a point of
 * HERSHEY_PEN_UP on both axes ends one polyline and starts the next.
 * `adv` is the glyph's advance. The table is generated by
 * tools/hershey_gen.py (the acknowledgment the data requires is in the
 * generated file and the generator).
 */
#ifndef FORGECTRL_FONT_HERSHEY_H
#define FORGECTRL_FONT_HERSHEY_H

#define HERSHEY_FIRST   32
#define HERSHEY_NGLYPH  95
#define HERSHEY_CAP     662
#define HERSHEY_PEN_UP  (-32768)

typedef struct {
    short adv;
    unsigned short first;
    unsigned short count;
} hershey_glyph_t;

extern const short hershey_pts[][2];
extern const hershey_glyph_t hershey_glyphs[HERSHEY_NGLYPH];
extern const unsigned hershey_npts;

#endif
